In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,23]])
arr.shape




(2, 5)

In [ ]:
import numpy as np
ar= np.arange(1,9,2).reshape(2,2)
ar

array([[1, 3],
       [5, 7]])

In [ ]:
import numpy as np
a = np.arange (0,6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b= np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
c=np.concatenate((a,b),axis=1)
c

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
d=np.stack((a,b),axis = 1 )
d


array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])

In [ ]:
import numpy as np

empty_array = np.array([],[])
print(empty_array)

[]


In [ ]:
one_arr= np.ones((4,2))
one_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arr1=np.full((2,3),(6))
arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
arr_zeros = np.zeros_like(arr1)
arr_zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr_ones = np.ones_like(arr1)
arr_ones

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.
#{Hint: np.array()}

new_list = [1,2,3,4]
np_array = np.array(new_list)
np_array

array([1, 2, 3, 4])

In [ ]:
#1. Create an array with values ranging from 10 to 49.
#{Hint:np.arrange()}.
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
arrr= np.arange (0,8).reshape(2,4)
arrr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
eye=np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4. Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
random_array = np.random.random(30)
mean_value = random_array.mean()
mean_value

0.4946942662212036

In [ ]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.
arr= np.arange(0,100).reshape(10,10)
print(arr)
min_value = arr.min()
max_value = arr.max()
print(min_value)
print(max_value)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
0
99


In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.
arr = np.zeros((10))
arr
arr[4]=1
arr


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
reversed_arr


array([0, 4, 0, 0, 2, 1])

In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.
a=np.zeros((4,4))
arr=np.pad(a,pad_width=1,mode='constant',constant_values=1)
arr


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
 #9. Create a 8X8 matrix and fill it with a checkerboard pattern
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2, 1::2]=1
a



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem 3 _Array operations

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
#1
# Add two array

x = np.array([[1,2],[3,5]]) ,
y = np.array([[5,6],[7,8]]) ,
add = np.add(x,y)
add



array([[[ 6,  8],
        [10, 13]]])

In [ ]:
# 2
# Substract two array
v = np.array([9,10]) ,
w = np.array([11,12])
sub = np.subtract(v,w)
sub


array([[-2, -2]])

In [ ]:

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

x_multiplied = x * 2
y_multiplied = y * 2
v_multiplied = v * 2
w_multiplied = w * 2

print("x multiplied by 2:\n", x_multiplied)
print("y multiplied by 2:\n", y_multiplied)
print("v multiplied by 2:\n", v_multiplied)
print("w multiplied by 2:\n", w_multiplied)


x multiplied by 2:
 [[ 2  4]
 [ 6 10]]
y multiplied by 2:
 [[10 12]
 [14 16]]
v multiplied by 2:
 [18 20]
w multiplied by 2:
 [22 24]


In [ ]:
#4
# Find the square of each element of the array.

import numpy as np

x_square = np.square(x),
y_square = np.square(y),
v_square = np.square(v),
w_square = np.square(w),

print("Square of x " , x_square),
print("Square of y " , y_square),
print("Square of v " , v_square),
print("Square of w " , w_square)

Square of x  (array([[ 1,  4],
       [ 9, 25]]),)
Square of y  (array([[25, 36],
       [49, 64]]),)
Square of v  (array([ 81, 100]),)
Square of w  (array([121, 144]),)


In [ ]:
#5
# Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_v_w = np.dot(v, w),
dot_x_v = np.dot(x, v),
dot_x_y = np.dot(x,y),

print("Dot product of v and w:",dot_v_w),
print("Dot product of x and v:", dot_x_v),
print("Dot product of x and y:\n", dot_x_y)

Dot product of v and w: (219,)
Dot product of x and v: (array([29, 77]),)
Dot product of x and y:
 (array([[19, 22],
       [50, 58]]),)


In [ ]:
#6
#  Concatenate x(and)y along row and Concatenate v(and)w along column.
#  {Hint:try np.concatenate() or np.vstack() functions.

concatenated_xy = np.concatenate((x, y), axis=0)
concatenated_vw = np.vstack((v, w))
print("Concatenated x and y along rows:\n", concatenated_xy)
print("Concatenated v and w along columns:\n", concatenated_vw)


Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 10]
 [11 12]]


Concatenated_xy = np.concatenate((x, y),) why i am getting error ?

The error occurs because the np.concatenate() function requires the axis parameter.Axis is set to 0, which means concatenation along the first axis (rows)

In [ ]:
# 1. Prove A * A^-1 = I
import numpy as np

A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 = I:\n", identity_matrix)


# 2. Prove AB = BA
B = np.array([[5, 6], [7, 8]])  # Example matrix
AB = np.dot(A, B)  # Compute AB
BA = np.dot(B, A)  # Compute BA
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))


# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)
print("(AB)^T == B^T A^T:", np.array_equal(AB_T, BT_AT))



A * A^-1 = I:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
AB:
 [[19 22]
 [43 50]]
BA:
 [[23 34]
 [31 46]]
AB == BA: False
(AB)^T:
 [[19 43]
 [22 50]]
B^T A^T:
 [[19 43]
 [22 50]]
(AB)^T == B^T A^T: True


In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure the time taken for element-wise addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()

print("Time taken for element-wise addition using Python lists:", end_time - start_time, "seconds")


Time taken for element-wise addition using Python lists: 0.27681636810302734 seconds


In [ ]:
import numpy as np
import time

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time, "seconds")


Time taken for element-wise addition using NumPy arrays: 0.004784822463989258 seconds


In [ ]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()

print("Time taken for element-wise multiplication using Python lists:", end_time - start_time, "seconds")


Time taken for element-wise multiplication using Python lists: 0.15594100952148438 seconds


In [ ]:
import numpy as np
import time

array1 = np.arange(100000)
array2 = np.arange(100000)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time, "seconds")


Time taken for element-wise multiplication using NumPy arrays: 0.0004138946533203125 seconds


In [ ]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()

print("Dot product using Python lists:", dot_product_list)
print("Time taken using Python lists:", end_time - start_time, "seconds")


Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.1730642318725586 seconds


In [ ]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()

print("Dot product using Python lists:", dot_product_list)
print("Time taken using Python lists:", end_time - start_time, "seconds")


Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.31844496726989746 seconds


In [25]:
import time

matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
end_time = time.time()

print("Time taken for matrix multiplication using Python lists:", end_time - start_time, "seconds")


Time taken for matrix multiplication using Python lists: 207.44330549240112 seconds


In [26]:
import numpy as np
import time

array1 = np.arange(10000).reshape(100, 100)
array2 = np.arange(10000).reshape(100, 100)

start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()

print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time, "seconds")


Time taken for matrix multiplication using NumPy arrays: 0.0018246173858642578 seconds
